### ISSUE TITLE
No error exit code is provided to shell when a file cannot be added to library from file list

### ISSUE THREAD

**Issue by JanWillemVanHelden** [abekermsx/makelib#1]
I use makelib.exe in shell scripts.
Upon completion of the makelib.exe program my script checks if the exit code was anything different than 0 and breaks if so.
I noticed that when a file that is part of the file list added to makelib.exe is not present, makelib.exe exits, but does not exit with an error code, so the script does not break.

Can you please exit with an error code if a problem occurs in makelib.exe

**Comment by abekermsx** [comment]
Good point! I just updated the code to return error code 1 if there's a problem with the program arguments and error code 2 if some file doesn't exist.

**Comment by JanWillemVanHelden** [comment]
Excellent! Thanks for the quick turnaround.
